feature: support checking whether there are Chinese links on english …
meathill/site-validator pull request #2
Opened 2020-12-01 12:52 UTC by liwang2019

…pages and vice versa.

2020-12-01 13:13 UTC, meathill requested changes

2020-12-01 13:13 UTC, meathill commented on lib/traverse.js
> +  if(((sourceLang === 'cn' && chineseCount <= 10) || (sourceLang === 'en' && chineseCount > 10)) && !(source.replace('/cn/', '/en/') === url || url.replace('/cn/', '/en/') === source)) {
These conditions should be calculated into some variables, like this:

```js
const con1 = ....;
const con2 = ....;
const con3 = ....;
if (con1 && con2 || con3) {

}
```

2020-12-02 08:35 UTC, liwang2019 commented on index.js
> +    if (langNotMatch && langNotMatch.length !== 0) {
changed.

2020-12-02 08:36 UTC, liwang2019 commented on lib/traverse.js
> +  if(((sourceLang === 'cn' && chineseCount <= 10) || (sourceLang === 'en' && chineseCount > 10)) && !(source.replace('/cn/', '/en/') === url || url.replace('/cn/', '/en/') === source)) {
changed.

2020-12-02 08:45 UTC, meathill approved these changes
LGTM.

2020-12-02 08:45 UTC, merged